## Tasca S9.01. Creació de funcions, estructures de dades i bucles

Descripció
Resoldràs alguns problemes de la vida quotidiana aplicant les estructures de dades i control en Python.
Un client de l'empresa en la qual treballes demana una llista de programes molt senzills, però que li facilitarien molts processos.

Se’t demanarà que programis varies funcions. Per a fer l’entrega, hauràs d’entregar tant el codi de la funció:
def funcioexemple(variable1, variable2):
resultat = variable1 + variable2 # sumem les dues variables
return resultat

Com la seva execució per demostrar que funciona correctament, ensenyant-ne l’output:
funcioexemple(3, 8)

Intenta que tot el codi que generis sigui el més reproduïble possible.

**Nivell 1**

*1. Calculadora de l'índex de massa corporal*

Escriu una funció que calculi l'IMC ingressat per l'usuari/ària, és a dir, qui ho executi haurà d'ingressar aquestes dades. Pots obtenir més informació del seu càlcul en: 🔗 Índice de masa corporal IMC que es y como se calcula.

La funció ha de classificar el resultat en les seves respectives categories.

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduïdes per l’usuari/a no estan en el format adequat o no pren valors raonables.

In [ ]:
def pedir_valor(mensaje, minimo, maximo):
    """
    función validación de valores introducidos por el usuario, se repite hasta obtner dato dentro rango.
    input:
        mesaje pidiendo dato, valor mínimo de rango y valor máximo de rango.
    output:
        valor dentro del rango.    
    """
    while(True):
        try:
            valor = float(input(mensaje).replace(",","."))
            if minimo < valor <= maximo:
                break
            print("Valor introducido no válido.")
        except ValueError:
            print("Introduce valores numéricos.")
    return valor

def calculo_imc(peso, altura):
    """
    función para calcular índice de masa corporal y categorizar según resultado.
    input:
        peso: en kg
        altura: en metros
    output:
        None: print categoría y valor de imc
    """
    imc = round(peso/(altura**2),2)
    if imc < 18.5:
        categoria = "BAJO PESO"
    elif imc < 25:
        categoria = "PESO NORMAL"
    elif imc < 30:
        categoria = "SOBREPESO"
    else:
        categoria = "OBESIDAD"
    print(f"Tu IMC es: {imc}, categoría {categoria}")

In [29]:
calculo_imc(pedir_valor("Intoduce tu peso (kg): ", 0, 500), pedir_valor("Intoduce tu altura (m): ", 0, 3))

Tu IMC es: 5.57, categoría BAJO PESO

*2. Convertidor de temperatures*

Existeixen diverses unitats de temperatura utilitzades en diferents contextos i regions. Les més comunes són Celsius (°C), Fahrenheit (°F) i Kelvin (K). També existeixen altres unitats com Rankine (°Ra) i Réaumur (°Re).

Selecciona almenys 2 conversors, de tal manera que en introduir una temperatura retorni, com a mínim, dues conversions, de manera que es puguin guardar (recorda que un print() no es pot guardar mai).

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduides per l’usuari/a no estan en el format adequat.

(EXTRA): Pensa una manera d’emmagatzemar totes les possibles conversions en un sol objecte (Llista? Diccionari? DataFrame?) en comptes d’escriure molts if else en funció de la temperatura d’origen i la temperatura de destí.

In [16]:
def validar_temperatura():
    """
    función para introducir valor float de temperatura.
    input:
        None
    output:
        valor float temperatura actual.
    """
    while(True):
        try:
            temperatura_actual = float(input("Intoduce temperatura actual: ").replace(",","."))
            break
        except ValueError:
            print("Introduce valores válidos.")
    return temperatura_actual

def validar_escala_temperatura():
    """
    función para convertir temperaturas de las escalas celsius, fahrenheit y kelvin.
    input:
        None
    output:
        medida de temperatura actual.
    """
    while(True):
        try:
            escala_actual = input("Intoduce unidad temperatura actual (C/F/K): ").lower()
            if escala_actual in ("c", "f", "k", "celsius", "fahrenheit", "kelvin"):
                break
            print("Unidad no válida. Usa C, F o K.")
        except ValueError:
            print("Introduce valores válidos.")
    return escala_actual

def conversor_temperatura(temperatura, medida):
    """
    función para convertir temperaturas de las escalas celsius, fahrenheit y kelvin.
    input:
        temperatura: float
        medida: "celsius" o "c", "fahrenheit" o "f", "kelvin" o "k".
    output:
        diccionario con conversiones de temperatura.
    """
    dicc_conversiones = {"celsius":{"fahrenheit":round((temperatura*1.8+32),2), "kelvin":round((temperatura+273.15),2)},
                        "fahrenheit":{"celsius":round(((temperatura-32)/1.8),2), "kelvin":round((((temperatura-32)/1.8)+273.15),2)},
                        "kelvin":{"celsius":round((temperatura-273.15),2), "fahrenheit":round(((temperatura-273.15)*1.8+32),2)}
                        }
    
    if medida == "c" or medida == "celsius":
        return dicc_conversiones["celsius"]
    elif medida == "f" or medida == "fahrenheit":
        return dicc_conversiones["fahrenheit"]
    elif medida == "k" or medida == "kelvin":
        return dicc_conversiones["kelvin"]
    else:
        print("Introduce unidad de temperatura válida.")

In [31]:
temperatura_actual = validar_temperatura()
escala_actual = validar_escala_temperatura()
conversion_temperatura = conversor_temperatura(temperatura_actual, escala_actual)
print(temperatura_actual, "grados", escala_actual.upper(), "equivale a", conversion_temperatura)

25.0 grados C equivale a {'fahrenheit': 77.0, 'kelvin': 298.15}

*3. Comptador de paraules d'un text.*

Escriu una funció que donat un text, mostri les vegades que apareix cada paraula. Intenta que es gestionin totes les casuístiques possibles que facin que el programa no funcioni correctament.

(EXTRA): Quina és la llargada mitjana de les paraules del text que has escrit? “Hola com va?” hauria de retornar (4+3+2) / 3 = 3

In [18]:
import string

def palabras_lista(texto):
    """
    función para convertir texto en lista de palabras.
    input:
        texto: input de string.
    output:
        lista de palabras sin puntuaciones.
    """
    if not texto.split():
        return []
    texto_low = texto.lower()
    sin_puntuacion = str.maketrans("", "", string.punctuation + "¿¡")
    texto_limpio = texto_low.translate(sin_puntuacion)
    return texto_limpio.split()

def contador_palabras(lista):
    """
    función para contar repecticiones de palabras dentro de un texto.
    input:
        lista de palabras.
    output:
        diccionario que cuenta cuántas veces se repite cada palabra.
    """
    lista_palabras = palabras_lista(lista)
    dicc_contador = {}
    for palabra in lista_palabras:
        if palabra not in dicc_contador:
            dicc_contador[palabra] = 1
        else:
            dicc_contador[palabra] += 1
    return dicc_contador

def largo_medio_palabras(lista):
    """
    función para calcular la longitud media de las palabras de nuestro texto.
    input:
        lista de palabras.
    output:
        longitud media de las palabras de la lista.
    """
    lista_palabras = palabras_lista(lista)
    if len(lista_palabras) == 0:
        print("La lista está vacía.")
        return 0
    total_letras = sum(len(palabra) for palabra in lista_palabras)
    return round(total_letras/len(lista_palabras),2)

In [21]:
while(True):
    frase = input("Introduce un texto: ")
    print(f"Tu texto es: {frase}")
    resultado = contador_palabras(frase)
    print(f"El conteo de cada palabra es: {resultado}")
    media = largo_medio_palabras(frase)
    print(f"La longitud media de las palabras es de {media} caracteres.")
    break
else:
    print("Introduce un texto válido.")

Tu texto es: Hola que tal? como estás? hola, bien
El conteo de cada palabra es: {'hola': 2, 'que': 1, 'tal': 1, 'como': 1, 'estás': 1, 'bien': 1}
La longitud media de las palabras es de 3.86 caracteres.

*4. Diccionari invers (amb possibilitat de duplicats)*

Resulta que el client té una enquesta molt antiga que s'emmagatzema en un diccionari i els resultats els necessita al revés, és a dir, intercanviant les claus i els valors. Els valors i claus en el diccionari original són únics; si aquest no és el cas, la funció hauria d'imprimir un missatge d'advertiment, juntament amb una llista amb els valors associats a la clau repetida.

In [28]:
def diccionario_inverso(diccionario):
    """
    función para invertir la clave-valor de un diccionario.
    input:
        diccionario inicial con clave-valor.
    output:
        diccionario que invierte la clave-valor del diccionario inicial, el valor pasa a ser la clave.
        Tiene en cuenta posibles repeticiones de valor.
    """
    if not isinstance(diccionario, dict):
        return print("Introduce un diccionario.")
    
    dicc_final = {}
    duplicados = {}

    for clave, valor in diccionario.items():
        if valor not in dicc_final:
            dicc_final[valor] = clave
        else:
            if isinstance(dicc_final[valor], list):
                dicc_final[valor].append(clave)
            else:
                dicc_final[valor] = [dicc_final[valor], clave]
            duplicados[valor] = dicc_final[valor]
    
    for valor, clave in duplicados.items():
        print(f"La nueva clave {valor} estaba repetida en {dicc_final[valor]}")
    
    return dicc_final

In [8]:
diccionario_prueba = {"a":1, "b":2, "c":2, "d":2}
diccionario_actualizado = diccionario_inverso(diccionario_prueba)
print(f"El nuevo diccionario es: {diccionario_actualizado}")

La nueva clave 2 estaba repetida en ['b', 'c', 'd']
El nuevo diccionario es: {1: 'a', 2: ['b', 'c', 'd']}

**Nivell 2**

*1. Comptador i endreçador de paraules d'un text.*

El client va quedar content amb el comptador de paraules, però ara vol llegir arxius TXT i que calculi la freqüència de cada paraula ordenades dins de les entrades habituals del diccionari segons la lletra amb la qual comencen, és a dir, les claus han d'anar de la A a la Z i dins de la A hem d'anar de la A la Z. Per exemple, per a l'arxiu "tu_me_quieres_blanca.txt" la sortida esperada seria:

In [29]:
import string

def conteo_palabras_az_txt(txt):
    """
    función para ordenar alfabéticamente y contar las palabras de un texto.
    input:
        archivo.txt
    output:
        diccionario que cuenta cuantas veces sale cada palabra y las ordena alfabéticamente.
    """
    dicc_conteo = {}
    with open(txt, 'r', encoding='utf-8') as archivo:
        texto = archivo.read()
        texto_low = texto.lower()
        sin_puntuacion = str.maketrans("", "", string.punctuation + "¿¡")
        texto_limpio = texto_low.translate(sin_puntuacion)
        palabras = texto_limpio.split()
        
        for palabra in palabras:
            if palabra not in dicc_conteo:
                dicc_conteo[palabra] = 1
            else:
                dicc_conteo[palabra] += 1
    
    dicc_alfabetico = {}

    for palabra in sorted(dicc_conteo.keys()):
        inicial = palabra[0]
        if inicial not in dicc_alfabetico:
            dicc_alfabetico[inicial] = {}
        dicc_alfabetico[inicial][palabra] = dicc_conteo[palabra]

    return dicc_alfabetico

In [30]:

conteo_palabras_az_txt("tu me quieres blanca.txt")

{'a': {'a': 3,
  'agua': 1,
  'al': 2,
  'alba': 4,
  'alcobas': 1,
  'alimenta': 1,
  'alma': 1,
  'amarga': 1,
  'azucena': 1},
 'b': {'baco': 1,
  'banquete': 1,
  'bebe': 1,
  'blanca': 3,
  'boca': 1,
  'bosques': 1,
  'buen': 1},
 'c': {'cabañas': 1,
  'carnes': 2,
  'casta': 3,
  'cerrada': 1,
  'con': 4,
  'conservas': 1,
  'copas': 1,
  'corola': 1,
  'corriste': 1,
  'cuando': 2,
  'cubierto': 1,
  'cuerpo': 1,
  'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
  'ellas': 1,
  'en': 4,
  'engaño': 1,
  'enredada': 1,
  'entonces': 1,
  'escarcha': 1,
  'espumas': 1,
  'esqueleto': 1,
  'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
  'hacia': 1,
  'haya': 1,
  'hayas': 1,
  'hermana': 1,
  'hombre': 1,
  'hubiste': 1,
  'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
  'labios': 1,
  'las': 7,
  'lo': 2,
  'los': 4,
  'luna': 1,
  'lévate': 1,
  'límpiate': 1},
 'm': {'mano': 1,
  'manos': 1,
  'margarita': 1,
  'me': 10,
  'mi': 1,
  'mieles': 1,
  'milagros': 1,
  'mojada': 1,
  'montaña': 1,
  'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone': 2,
  'perfume': 1,
  'por': 2,
  'pretendes': 3,
  'preténdeme': 3,
  'puesto': 1,
  'pájaros': 1,
  'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
  'tejidos': 1,
  'tenue': 1,
  'tierra': 1,
  'toca': 1,
  'todas': 2,
  'todavía': 1,
  'tornadas': 1,
  'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5}}

*2. Conversió de tipus de dades.*

El client rep una llista de dades i necessita generar dues llistes, la primera on estaran tots els elements que es van poder convertir en flotants i l'altra on estan els elements que no es van poder convertir. Exemple de la llista que rep el client:

In [36]:
def definir_float(objeto):
    """
    función para definir si un objeto es float o no.
    input:
        lista con diversos elementos.
    output:
        True o False en función de si es float.
    """
    try:
        float(objeto)
        return True
    except (ValueError):
        return False

def separar_float(lista):
    """
    función para separar elementos float de los no float de una lista.
    input:
        lista con diversos elementos.
    output:
        dos listas, una con todos los elementos float y otra con los elementos no float de la lista original.
    """
    if not isinstance(lista, list):
       return print("Introduce una lista.")
        
    lista_float = []
    lista_no_float = []

    for elemento in lista:
        if isinstance(elemento, (list, tuple)):
            for subelemento in elemento:
                if definir_float(subelemento):
                    lista_float.append(float(subelemento))
                else:
                    lista_no_float.append(subelemento)
        else:
            if definir_float(elemento):
                lista_float.append(float(elemento))
            else:
                lista_no_float.append(elemento)

    return lista_float, lista_no_float

In [ ]:
lista_original = [ '1.3', 'one' , '1e10' , 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,'3','3.4']]
try:
    listas_separadas = separar_float(lista_original)
    print(listas_separadas)
except NameError:
    print("La lista no está definida.") 
#He corregido el convertir los números de la lista_float a tipo float.

([1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4], ['one', 'seven', '3-1/2', 'not-a-number'])

**Nivell 3**

*1. Generador de Contrasenyes*

Explora el funcionament del mòdul random de la llibreria numpy. 🔗 Random module in NumPy

En aquest punt, el client ha detectat un problema amb les contrasenyes que utilitzen els seus treballadors. Asdf1234, dates d’aniversari o similars. Per a solucionar-ho ens ha encarregat una funció de Python que generi contrasenyes més segures. La funció ha de dependre dels següents paràmetres:

longitud (int): Longitud de la contrasenya
majuscules (bool = True): Si hi ha d’aparèixer majúscules
minuscules (bool = True): Si hi ha d’aparèixer minúscules
numeros (bool = True): Si hi ha d’aparèixer números
signes (bool = False): Si hi ha d’aparèixer caràcters especials (,-$? o similars)
Així doncs, si executem la funció de la següent manera:

crear_contrasenya(10, True, True, True, True)

Hauríem d’obtenir un output (que hem de poder guardar) de l’estil:

9Er,5Vn8P$

Assegura’t que es compleixin tots els criteris, i que aquestes contrasenyes siguin realment aleatòries.

(EXTRA) Explora com podríem fer que la funció copiés la contrasenya automàticament al porta papers de l’ordinador (com si l’haguéssim seleccionat i fet ctrl+copy).

In [27]:
import numpy as np
import string
import pyperclip

def definir_parametros_password():
    """
    función para definir longitud y qué parámetros debe contener la contraseña.
    input: 
        user_lon (int), user_mayus (Activar = 1/ Desactivar = 0), user_minus (Activar = 1/ Desactivar = 0), 
        user_num (Activar = 1/ Desactivar = 0), user_sign (Activar = 1/ Desactivar = 0)
    output:
        tupla con user_lon, user_mayus, user_minus, user_num, user_sign.
    """
    try:
        user_lon = int(input("Longitud password (número entero): "))
        if user_lon <= 0:
            raise ValueError("LONGITUD_ERRONEA")

        user_mayus = input("Mayúsculas (Activar = 1/ Desactivar = 0): ") == "1"
        user_minus = input("Minúsculas (Activar = 1/ Desactivar = 0): ") == "1"
        user_num = input("Números (Activar = 1/ Desactivar = 0): ") == "1"
        user_sign = input("Signos (Activar = 1/ Desactivar = 0): ") == "1"
        if not (user_mayus or user_minus or user_num or user_sign):
            raise ValueError("SIN_CARACTERES")

        return user_lon, user_mayus, user_minus, user_num, user_sign

    except ValueError as e:
        if str(e) == "LONGITUD_ERRONEA":
            print("Introduce una longitud numérica superior a 0.")
        elif str(e) == "SIN_CARACTERES":
            print("Debes activar como mínimo un tipo de carácter.")
        else:
            print("Introduce un número válido para la longitud.")

def crear_password(longitud, mayusculas, minusculas, numeros, signos):
    """
    función para crear contraseñas con carácteres concretos, longitud establecida y copiar contraseña en portapapeles.
    input: 
        longitud password(int), mayúsculas(0/1), minúsculas(0/1), números(0/1), signos(0/1).
    output:
        password aleatorio.
    """
    caracteres = ""
    if mayusculas:
        caracteres += string.ascii_uppercase
    if minusculas:
        caracteres += string.ascii_lowercase
    if numeros:
        caracteres += string.digits
    if signos:
        caracteres += string.punctuation

    clave = "".join(np.random.choice(list(caracteres), size=longitud))
    pyperclip.copy(clave)
    return clave

In [ ]:
user_lon, user_mayus, user_minus, user_num, user_sign = definir_parametros_password()
password = crear_password(user_lon, user_mayus, user_minus, user_num, user_sign)
print(password)

#No he tenido en cuenta que debe haber mínimo un carácter de cada tipo activado.

;%^=HE"&7<

*2. Processament de dades simple*

Una companya de feina ens ha demanat un favor, aprofitant que sap que estem aprenent a programar. Té un històric de partits de futbol català en un fitxer, on hi ha emmagatzemat els noms dels equips i els resultats. Necessita que processem les dades de manera automàtica, per extreure’n els resultats que necessita.

Utilitza el fitxer "historic_partits.txt"

Necessita un programa que retorni:

El nombre total de gols que ha fet cada equip.
El nom de l’equip més golejador.
El nom de l’equip més golejat
La classificació global (cada victòria: 3 pts, empat 1 pts, derrota 0 pts)
Com a referència, els equips amb més punts serien els següents:

Pots utilitzar el format que et sigui més convenient.

In [ ]:
import pandas as pd

def cargar_resultados(archivo):
    """
    función para cargar datos del archivo txt con resultados.
    input: 
        nombre archivo txt con los resultados de los partidos.
    output:
        df que separa equipo_local, goles_favor, goles_contra y equipo_visitante.
    """
    resultados = pd.read_csv(archivo, sep='\t', header=None)
    goles = resultados[1].str.split('-', expand=True).astype(int)
    resultados = pd.DataFrame({ "equipo_local": resultados[0],
                                "goles_favor": goles[0],
                                "goles_contra": goles[1],
                                "equipo_visitante": resultados[2]})
    return resultados

def equipo_fila_resultados(df_resultados):
    """
    función que separa datos en df local y df visitante, con misma estructura para concatenar en un solo df.
    input: 
        df con campos equipo_local, goles_favor, goles_contra y equipo_visitante.
    output:
        df con campos equipo, goles, goles_encajados y condición (local o visitante).
    """
    local = df_resultados.rename(columns={ "equipo_local": "equipo",
                                        "goles_favor": "goles",
                                        "goles_contra": "goles_encajados"}).assign(condicion="local")[["equipo", "goles", "goles_encajados", "condicion"]]
    visitante = df_resultados.rename(columns={ "equipo_visitante": "equipo",
                                            "goles_contra": "goles",
                                            "goles_favor": "goles_encajados"}).assign(condicion="visitante")[["equipo", "goles", "goles_encajados", "condicion"]]

    return pd.concat([local, visitante], ignore_index=True)

def columnas_puntos(df_equipo_fila):
    """
    función que crea campos de partidos ganados, empatados y perdidos, junto con columna calculada de puntos.
    input: 
        df con campos equipo, goles, goles_encajados y condición (local o visitante).
    output:
        df con campos equipo, goles, goles_encajados, condición, ganados, empatados, perdidos y puntos.
    """
    df_equipo_fila["ganados"] = (df_equipo_fila["goles"] > df_equipo_fila["goles_encajados"]).astype(int)
    df_equipo_fila["empatados"] = (df_equipo_fila["goles"] == df_equipo_fila["goles_encajados"]).astype(int)
    df_equipo_fila["perdidos"] = (df_equipo_fila["goles"] < df_equipo_fila["goles_encajados"]).astype(int)

    df_equipo_fila["puntos"] = df_equipo_fila["ganados"]*3 + df_equipo_fila["empatados"]*1
    return df_equipo_fila #al final adjunto corrección más eficiente de esta parte, para no crear tantas columnas.

def clasificacion_equipos(df_equipos_puntos):
    """
    función agrupar datos por equipos y ordenar clasificación por puntos.
    input: 
        df con campos equipo, goles, goles_encajados, condición, ganados, empatados, perdidos y puntos.
    output:
        df con campos equipo, ganados, empatados, perdidos, goles, goles_encajados y puntos, ordenado por puntos.
    """
    clasificacion = df_equipos_puntos.groupby("equipo")[["ganados", "empatados", "perdidos", "goles", "goles_encajados", "puntos"]].sum().sort_values(["puntos"], ascending = False).reset_index()
    return clasificacion

def resumen_clasificacion(df_clasificacion):
    """
    función para mostrar el equipo más goleador, el más goleado, los 5 con más goles y la clasificación.
    input: 
        df con clasificación de los equipos.
    output:
        None : print de los datos resumen sobre la clasificación.
    """
    equipo_goles = df_clasificacion[["equipo", "goles"]].sort_values(["goles"], ascending=False)
    equipo_más_goleador = df_clasificacion.loc[df_clasificacion["goles"].idxmax(), ["equipo", "goles"]].to_frame().T
    equipo_más_goleado = df_clasificacion.loc[df_clasificacion["goles_encajados"].idxmax(), ["equipo", "goles_encajados"]].to_frame().T

    print("El equipo más goleador es:")
    display(equipo_más_goleador)
    print("El equipo más goleado es:")
    display(equipo_más_goleado)
    print("Los 5 equipos con más goles a favor son:")
    display(equipo_goles.head())
    print("La clasificación es:")
    display(df_clasificacion)

def resultados_clasificacion(archivo):
    """
    función con varias funciones para limpieza de datos.
    input: 
        nombre archivo txt con los resultados de los partidos.
    output:
        None : print de los datos resumen sobre la clasificación.
    """
    df_resultados = cargar_resultados(archivo)
    df_equipo_fila = equipo_fila_resultados(df_resultados)
    df_equipos_puntos = columnas_puntos(df_equipo_fila)
    clasificacion = clasificacion_equipos(df_equipos_puntos)
    resumen_clasificacion(clasificacion)

In [5]:
resultados_clasificacion("historic partits.txt")

El equipo más goleador es:

     equipo goles
5  Figueres   161

El equipo más goleado es:

       equipo goles_encajados
9  Vilafranca             172

Los 5 equipos con más goles a favor son:

       equipo  goles
5    Figueres    161
1  Llagostera    159
9  Vilafranca    157
3    Cornellà    147
7    Terrassa    147

La clasificación es:

,equipo,ganados,empatados,perdidos,goles,goles_encajados,puntos
0,Girona FC,31,3,13,139,94,96
1,Llagostera,29,7,20,159,142,94
2,Sabadell,26,7,15,141,121,85
3,Cornellà,25,7,22,147,146,82
4,RCD Espanyol,23,11,21,131,144,80
5,Figueres,23,10,23,161,154,79
6,Lleida Esportiu,23,6,23,129,133,75
7,Terrassa,20,14,23,147,164,74
8,FC Barcelona,22,7,15,125,115,73
9,Vilafranca,20,12,25,157,172,72
10,Badalona,18,14,16,134,124,68
11,Reus Deportiu,20,8,16,119,111,68
12,Nàstic de Tarragona,20,8,27,130,148,68
13,Granollers,21,4,24,122,117,67
14,Olot,18,10,26,132,144,64
15,Sant Andreu,17,11,25,123,134,62
16,Manlleu,16,9,18,106,118,57
17,Cerdanyola,17,5,28,117,133,56
18,Prat,16,8,21,106,111,56
19,Europa,12,5,16,93,93,41

In [ ]:
#ANNEXO:
#Corrección: He buscado como sería solución más eficiente:
def columnas_puntos(df_equipo_fila):
    """
    función que crea campos de partidos ganados, empatados y perdidos,
    junto con columna calculada de puntos.
    """
    return (
        df_equipo_fila
        .assign(
            ganados=lambda df: (df["goles"] > df["goles_encajados"]).astype(int),
            empatados=lambda df: (df["goles"] == df["goles_encajados"]).astype(int),
            perdidos=lambda df: (df["goles"] < df["goles_encajados"]).astype(int),
        )
        .assign(
            puntos=lambda df: df["ganados"] * 3 + df["empatados"]
        )
    )